### ISSUE TITLE
Message response by GetReceivedSmsLogs getting all messages all time using pull method 

### ISSUE THREAD

**Issue by namjithwisilica** [infobip/infobip-api-java-client#10]
I have sent messages and reading messages by a cron job and always getting all messages instead of new messages (unread). Please help. Below is the code i am using.
`  MOLogsResponse moLogsResponse = this.client.execute(null, null, null, 10, null);`

**Comment by VilimKrajinovic** [comment]
`GetReceivedSmsLogs `will always return all messages. If you want to get only new messages and once you read them you want them to not be readable anymore use delivery reports by calling the `GetReceivedMessages `client

**Comment by namjithwisilica** [comment]
Thanks a lot.

**Comment by abbasabidi85** [comment]
How do i use GetRecievedSmsLog to get sms log? I'm new to it i want to implement it to get the logs of sms sent and then use the api response in some way to represent the logs inside app. please help if anyone can.
