### ISSUE TITLE
Howto upgrade from 2.x to 3.0

### ISSUE THREAD

**Issue by bwaldvogel** [infobip/infobip-api-java-client#15]
The [release notes of 3.0.0](https://github.com/infobip/infobip-api-java-client/releases/tag/3.0.0) state this release contains **breaking changes**.
Is there some documentation/guide/tips that explains howto upgrade from `2.3.0` to `3.0.0`?

**Comment by kiselica-aldin** [comment]
Hello @bwaldvogel
to cut to the chase - no, we didn't prepare such a document for this major release.

The reason behind this is that (as noted in the release notes you referred to) version 3.0.0 is `completely different from the previous version`.

That includes the implementation part but also the naming of the APIs, model classes, methods... pretty much everything.
Hence, we could think of it as a completely different library, and such a document would be probably the same size as the actual lib itself.

To emphasize that, here is an example of SMS sending implementation for both of these versions.

> 2.x.x
```
	    SendSingleTextualSms client = new SendSingleTextualSms(new BasicAuthConfiguration(USERNAME, PASSWORD));
	    
	    SMSTextualRequest requestBody = new SMSTextualRequest();
	    requestBody.setFrom(FROM);
	    requestBody.setTo(Arrays.asList(TO, TO_2));
	    requestBody.setText(MESSAGE_TEXT);
	    
	    SMSResponse response = client.execute(requestBody);
```

> 3.x.x

```
	    SendSmsApi sendSmsApi = new SendSmsApi();

	    SmsTextualMessage smsMessage = new SmsTextualMessage()
	        .from(FROM)
	        .addDestinationsItem(new SmsDestination().to(TO))
	        .text(MESSAGE_TEXT);

	    SmsAdvancedTextualRequest smsMessageRequest = new SmsAdvancedTextualRequest().messages(
	       Collections.singletonList(smsMessage)
	    );

	    try {
	        SmsResponse smsResponse = sendSmsApi.sendSmsMessage(smsMessageRequest);
	    } catch (ApiException apiException) { }
```
For the smoothest transition at this point, I would suggest using the [QUICKSTART](https://github.com/infobip/infobip-api-java-client#quickstart) we prepared within the README file. Feel free to ask us anything in case you face some issues.

**Comment by bwaldvogel** [comment]
Ok, thanks for the explanation.
My question and especially your answer could anyway be useful for others who might have the same question ;)

**Comment by matheusnascgomes** [comment]
@kiselica-aldin What about the Basic Authorization, where do i set it up in version 3.x.x?

**Comment by kiselica-aldin** [comment]
So, in previous versions we had to provide the Authorization as a part of API instancing, like you saw in this first code snippet for `2.x.x`.
Now, the idea is to be able to use something called default configuration if you wish, or to keep sending it as a param (like before) if that works better for you for any reason.

For example, if you jump to the [Quickstart](https://github.com/infobip/infobip-api-java-client#quickstart) part of our README.md file you will see that we enable you to have something like this:

```
    Configuration.setDefaultApiClient(apiClient);
```

What it means is that after you create an instance of `ApiClient` class (will get to that in a second) you can set it on library level as a default meaning all your requests will use it out of the box without you having to specify it.

And for the authenticatiton part, if you wish to use App Auth, you can do it like this:

```
    ApiClient apiClient = new ApiClient();
    apiClient.setApiKeyPrefix("App");
    apiClient.setApiKey(API_KEY);
    apiClient.setBasePath(URL_BASE_PATH);

```

Same analogy goes if you want to use Basic Auth:

```
        ApiClient apiClient = new ApiClient();
        apiClient.setApiKeyPrefix("Basic");
        apiClient.setUsername(USER);
        apiClient.setPassword(PASS);
        apiClient.setBasePath(URL_BASE_PATH);
```

...or if you want to use `OAuth 2.0` or even `IBSSO` -> check here which [Authenticatiton](https://www.infobip.com/docs/essentials/api-authentication) options we support.

The idea is that you can create it once and set it as default so you don’t have to pass it as a param. In that case, as in initial comment, you can instantiate API like the following

```
	    SendSmsApi sendSmsApi = new SendSmsApi();
```

But, if for any reason you want to use separate ApiClient (auth) for some method you can pass it in constructor:

```
	    SendSmsApi sendSmsApi = new SendSmsApi(apiClient);
```


Hopefully this clears it out :)
