### ISSUE TITLE
maven-assembly-plugin causes duplicated classes.

### ISSUE THREAD

**Issue by dosuser** [infobip/infobip-api-java-client#2]
maven-assembly-plugin causes duplicated classes.
'infobip-api-java-client 1.1.1.jar' contains copied gson and retrofit souce code and maven dependency.

[jboss tattletale result.]
![tattletale](https://cloud.githubusercontent.com/assets/7863422/13949741/12e4a33c-f06a-11e5-8565-17b47f403322.PNG)

[maven dependency and jar]
![maven](https://cloud.githubusercontent.com/assets/7863422/13949925/49debef8-f06b-11e5-8298-dfe8f23fedfc.PNG)

blame ..
https://github.com/infobip/infobip-api-java-client/commit/675ea98a0fd85c3c3d6d4a76321257ef72be2728

**Comment by mats990** [comment]
Hi,
Version 1.1.2 with fix is released and deployed. From now on, main jar will be without dependencies.
If in any case there is need for jar with dependencies, please use classifer "jar-with-dependencies".

Kind regards
