### ISSUE TITLE
OMNI support in the infobip-api-java-client module

### ISSUE THREAD

**Issue by kyle-hong** [infobip/infobip-api-java-client#29]
hello.

I would like to use the infobip-api-java-client module to handle the [Send OMNI failover message](https://www.infobip.com/docs/api/channels/omni-failover/send-omni-failover-message), but there doesn't seem to be any related code in that module.

Is this something that is not supported by that module?

**Comment by ib-fsrnec** [comment]
Hi @kyle-hong,

I'm sorry for the late response. Unfortunately, OMNI failover is not supported by this library anymore. Could you maybe elaborate which channels do you plan to use through OMNI failover so we can eventually plan further updates?

Best regards,
Filip Srnec

**Comment by kyle-hong** [comment]
@ib-fsrnec 

I am using the Kakao Alarm Talk channel.
