### ISSUE TITLE
NoSuchMethodError when sending Whatsapp Text Message

### ISSUE THREAD

**Issue by SzymonPek** [infobip/infobip-api-java-client#31]
Hi Team,

We have strange behavior with Infobip Java Client and 4.0.0. when we want to send a WhatsApp text message to recipient in conversation already initiated scenario. 
According to your documentation we should use "SendWhatsAppApi" class but there is nothing like that in version 4.0.0:

<img width="812" alt="image" src="https://github.com/infobip/infobip-api-java-client/assets/144792205/2d8aa550-0b27-4550-8caf-7b90630c3271">

What we do is try to send message using following code:

>             WhatsAppTextMessage textMessage = new WhatsAppTextMessage()
>                     .from("ValidFrom")
>                     .to("ValidTO")
>                     .content(new WhatsAppTextContent().text("TEXT");
>                      textMessage.setNotifyUrl("url");
>             try {
>                 WhatsAppSingleMessageInfo whatsAppMessageInfo = whatsAppApi.sendWhatsAppTextMessage(textMessage).execute();
>                 processedResponse = processResponse(whatsAppMessageInfo, whatsappMessage);
>             } catch (ApiException e) {
>                 appEventHandler.error("Error sending single text message: ",e);
>             }
> 

 so by using WhatsAppApi class:                
` WhatsAppSingleMessageInfo whatsAppMessageInfo = whatsAppApi.sendWhatsAppTextMessage(textMessage).execute();`

but we're getting error:

> Exception in thread “Thread-12” java.lang.NoSuchMethodError: ‘okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)’
> 	at com.infobip.RequestFactory.buildRequestBody(RequestFactory.java:159)
> 	at com.infobip.RequestFactory.create(RequestFactory.java:89)
> 	at com.infobip.ApiClient.buildCall(ApiClient.java:409)
> 	at com.infobip.ApiClient.execute(ApiClient.java:336)
> 	at com.infobip.api.WhatsAppApi$SendWhatsAppTextMessageRequest.execute(WhatsAppApi.java:1397)

Could you help us identify if there is wrong configuration on our side or there is bug in client?

**Comment by SzymonPek** [comment]
It might look like a bug in RequestFactory where instead of providing first MediaType then String as arguments, you provide String first and then MediaType:

`return RequestBody.create(json.serialize(bodyRepresentation), requestMediaType);
`

**Comment by lvukadinovic-ib** [comment]
Hi @SzymonPek,

first of all, thank you for using our library. 

Regarding use of "SendWhatsAppApi" class, it was replaced with "WhatsAppApi" class in the version 4.0.0., but unfortunately it seems that the example hasn't been updated to reflect that.

Regarding the java.lang.NoSuchMethodError, can you check which version of the okhttp dependency (com.squareup.okhttp3:okhttp) are you using? It should be 4.10.0 in the version 4.0.0 of our library. Previously it was 3.14.9 so it could be that it wasn't properly updated.

**Comment by SzymonPek** [comment]
Hi there.
In our project we don't use okhttp3 so it based on dependency defined in your Java Client. And from what I can see in your pom.xml it is using 4.10.0. so should be fine.

In project's gradle dependency tree we checked that it was still pushed to 3.14.9 ( when no other dependency was using Okhttp3):
![image](https://github.com/infobip/infobip-api-java-client/assets/144792205/94e4ef6b-a5c8-48fd-902a-6b14b79d22e0)

Not sure if this is something wrong with your package configuration but when we added explicite implementation of okhttp3 to build.gradle, it worked:
![image](https://github.com/infobip/infobip-api-java-client/assets/144792205/4ca09197-3e7a-4769-8af3-fe3351a5d630)

**Comment by lvukadinovic-ib** [comment]
Hi,

this probably means okhttp dependency version defined in our pom.xml is being overridden from somewhere else. For example, if your project is a Spring Boot app and you have included spring-boot-starter-parent then that performs dependency management and unless you explicitly declare which version of okhttp you want, it will use the one defined in spring-boot-starter-parent.

**Comment by lvukadinovic-ib** [comment]
Hi @SzymonPek ,

since there is no response, I'll be marking this as closed. Feel free to reopen this issue if the problem persists.

**Comment by lvukadinovic-ib** [comment]
Hi @SzymonPek,

since there is no reply, I'll be marking this issue as closed. Feel free to reopen it if the problem persists.
