### ISSUE TITLE
Incorrect and incomplete documentation for SMS with 5.0.0

### ISSUE THREAD

**Issue by nvervelle** [infobip/infobip-api-java-client#48]
It seems the documentation has not been completely updated for SMS with 5.0.0.

I saw several issues : 

With the release notes : several unrelated classes are said to be replaced by IysRecipientType, but it seems to be a copy/paste

With the README for SMS :
* The SmsTextualMessage class and other classes seem to have been removed, but they are not mentioned in the release notes
* The [sample to send a SMS](https://github.com/infobip/infobip-api-java-client/blob/822eb08777ea72f932c18f800c31e16067f11159/README.md#send-an-sms) has been updated to deal with the removal of SmsTextualMessgae
* But the [documentation to receive sent SMS report](https://github.com/infobip/infobip-api-java-client/blob/822eb08777ea72f932c18f800c31e16067f11159/README.md#receive-sent-sms-report) still mentions SmsTextualMessage

That's the few things I saw when I tried to upgrade from 4.4.0 to 5.0.0

**Comment by ib-tjuhasz** [comment]
Hi @nvervelle,

Thank you for taking the time to report these issues and providing detailed feedback—it’s greatly appreciated!

We’ve reviewed the documentation and made updates to both the README and the CHANGELOG to address the inconsistencies you mentioned.

Thanks again for helping us improve!

Best regards,
Tamás Juhász
