### ISSUE TITLE
Wrong Authorization Header on the ApiKeyAuthConfiguration

### ISSUE THREAD

**Issue by jmadureira** [infobip/infobip-api-java-client#6]
The `infobip.api.config.ApiKeyAuthConfiguration` is assuming that the authorization header is `Api apiKey` when according to the [documentation](https://dev.infobip.com/docs/getting-started#authorization) it should be `App apiKey`

**Comment by hkozacinski** [comment]
Hi!

Thank you for noticing and reporting the issue. This was indeed a bug and is fixed now, so the issue will closed.
In case of any further questions or issues, feel free to contact us.

Kind regards,
Hrvoje
